with-expecter: True
dir: ./
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceName}}_test.go"
outpkg: "analrepo"
packages:
  github.com/godepo/pgrx/example:
    config:
      all: False
    interfaces:
      DB:
        config:
  github.com/jackc/pgx/v5:
    config:
      all: False
      include-regex: "Rows"